### PR TITLE
Presentation mode

### PR DESCRIPTION
**Pull request by egoist**
test

### CODE REVIEW

**Comment by egoist** [comment]
Todo:

- [ ] Hide header and footer in full screen
- [ ] Show progress indicator in full screen
- [ ] Enable arrow keys in full screen

**Comment by djyde** [comment]
it's good

**Comment by egoist** [comment]
I don't know if it's better to use https://github.com/hakimel/reveal.js/ , I will give a try first 😢

**Comment by tajpure** [comment]
I have tried that. There were so many compatibility issues with reveal.js and then I decided to implement it by myself . I don't think It's a good idea to integrate reveal.js into your project.

**Comment by egoist** [comment]
@tajpure Same idea 😂

**Pull request merged**
