### PR TITLE
Adding tooltips to footer buttons

### PR DESCRIPTION
**Pull request by matheusrocha89**
This PR adds tooltips to footer buttons. 

I think we can think on a better text for the tooltips.

### CODE REVIEW

**Comment by egoist** [comment]
what do you think of using http://kushagragour.in/lab/hint/ to style the tooltip?

**Comment by matheusrocha89** [comment]
@egoist I think it's good, I can put on this PR. What do you think about the phrases?

**Comment by egoist** [comment]
What about `editor only` ` default` `preview only`

**Comment by matheusrocha89** [comment]
It's better, I just put those ones because I really did not understand what that buttons really do

**Comment by egoist** [comment]
You don't need to add hint.css to `index.html` since we didn't bundle `./node_modules` with the app, simply add hint.css to `src/app.vue` like below:

```vue
<style src="hint.css/hint.css"></style>
```

**Comment by matheusrocha89** [comment]
I was doing that right now 😄

**Comment by egoist** [comment]
I've merged it into dev branch. https://github.com/egoist/eme/commits/dev

**Pull request closed without merging**
