### PR TITLE
Tab drag indicator

### PR DESCRIPTION
**Pull request by Perkovec**
[Enjoy](https://github.com/egoist/eme/pull/31#issuecomment-240371404) 😉
ide

### CODE REVIEW

**Comment by egoist** [comment]
Something's weird 😅

test

**Comment by Perkovec** [comment]
Oh... wait

**Comment by Perkovec** [comment]
@egoist fixed

**Comment by egoist** [comment]
You didn't handle the situation that drag over a non-tab element

**Comment by Perkovec** [comment]
@egoist how should work in this situation? I can't understand

**Comment by egoist** [comment]
```js
this.handleDragEnd = e => {
  e.target.classList.remove('dragging', 'drag-over', 'drag-enter')
}
```

These classNames are only removed after a tab is dragged over another tab, but dragging everywhere else should also remove the classNames.

**Comment by egoist** [comment]
test

I cannot see the save status after dragging to the editor

**Comment by Perkovec** [comment]
@egoist [indicator](https://github.com/egoist/eme/pull/35#issuecomment-240424930) bug fixed, but [this](https://github.com/egoist/eme/pull/35#issuecomment-240422508) I can't understand still

**Comment by egoist** [comment]
Another issue, the `×` always shows:

test

Besides, it should refocus the current editor after tab resorted

**Comment by Perkovec** [comment]
@egoist ok, I can try. Same issue in VisualStudio Code 😄

**Comment by Perkovec** [comment]
@egoist test commits

**Pull request closed without merging**
